modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="farmersdelightintegration"
version="1.18.2-1.0.0"
displayName="Farmer's Delight Integration"
credits="vectorwing, iku_tv"
authors="minteyay"
description="Farmer's Delight mod integration"

[[dependencies.farmersdelightintegration]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.farmersdelightintegration]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.farmersdelightintegration]]
    modId="farmersdelight"
    mandatory=true
    versionRange="[1.18.2-1.2.0,)"
    ordering="AFTER"
    side="BOTH"
